### ISSUE TITLE
Provide optimized codes

### ISSUE THREAD

**Issue by emeryao** [mgechev/optimizing-apps-angular-demo#1]
Hi Minko
just watched the awsome video on [youtube](https://youtu.be/FjyX_hkscII) and finds the codes here  
but it seems that the codes in the master branch are the original demo codes before optimizing  
so could you please push the optimized codes up ?

Thanks

---
Sorry for my poor English

**Comment by mgechev** [comment]
You can check the worker branch, which contains the optimizations.

**Comment by emeryao** [comment]
got it, many thanks
